### PR TITLE
Use !default for inherit

### PR DESCRIPTION
**Pull request by francescobianco**
In this way, you can inherit inside a customization session with '@import'

### CODE REVIEW

**Comment by francescobianco** [comment]
Please @chilts @patrickhlauke @kylelogue use !default for all components
read this https://robots.thoughtbot.com/sass-default

**Comment by splitbrain** [comment]
@kylelogue Any hope to get this integrated?

**Comment by francescobianco** [comment]
@splitbrain @kylelogue Actually I start do work over a FORK called Handbook-UI
https://github.com/javanile/handbook-ui
please  @chilts @patrickhlauke   shake the project
For @splitbrain if you want to contribute on https://github.com/javanile/handbook-ui create an issue on Handbook-UI

**Comment by kylelogue** [comment]
This was resolved in the latest v0.0.8 release.  All SCSS variables are now declared using `!default`

**Pull request closed without merging**
