### PR TITLE
Update forms.scss

### PR DESCRIPTION
**Pull request by francescobianco**
use standard input types

### CODE REVIEW

**Comment by kylelogue** [comment]
Thanks for kicking this off!  I think this is the simple answer, but some of the fields like `date` need more specific styling.  Also, please include the re-compiled css in your pull request.

**Comment by bendog** [comment]
no movement on this in almost a year?

**Comment by cssworkshop** [comment]
@bendog fixed in https://github.com/kylelogue/mustard-ui/commit/146fc0a58969b64f03d0e9398ddae58ec5809747

**Comment by fitztrev** [comment]
@francescobianco Can you look at #43? The `range` input appears as a text input with a dot inside of it.

**Pull request closed without merging**
